name       : lbreakout2
version    : 2.6.5
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/lgames/lbreakout2/2.6/lbreakout2-2.6.5.tar.gz : 9104d6175553da3442dc6a5fc407a669e2f5aff3eedc5d30409eb003b7a78d6f
license    : GPL-2.0
component  : games.arcade
summary    : a breakout-style arcade game for Linux
description: |
    a breakout-style arcade game for Linux
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
setup      : |
    %configure --enable-sdl-net
build      : |
    %make
install    : |
    %make_install
